name: Test on Pull Request

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Lint and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run lint-staged
        run: npx lint-staged

      - name: Run Tests with Vitest
        run: npm run test
        env:
          CI: true
